### ISSUE TITLE
Ringing a bell while time is sped up causes a crash

### ISSUE THREAD

**Issue by Authrec** [Steveplays28/stevesrealisticsleep#46] opened 2023-09-08 02:46 UTC
To reproduce, sleep on a server with a sleeping percentage of 50, then have the non-sleeping player ring a bell, causing the server to crash.

**Crash Report**
```
net.minecraft.util.crash.CrashException: Ticking block entity
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:901) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:283) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-project-@-merged-named.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "hearingEntities" is null
```

**Comment by Steveplays28** [comment] 2023-09-09 00:40
Hi Authrec, thanks for the report. I'll look into this.

**Comment by Steveplays28** [comment] 2023-10-08 12:35
I'm unable to reproduce this issue.
I tested with Carpet's fake player feature, continuously ringing a bell, while a raid is happening and I'm sleeping. No crash occurred in that situation.

**Comment by Steveplays28** [comment] 2024-08-22 18:22
I'm closing this issue because I haven't been able to reproduce the crash.

**Closed by Steveplays28** 2024-08-22 18:22 UTC
Labels: bug, unable to reproduce, crash
